language: node_js
node_js: stable
sudo: false

install:
    - npm install -g tslint typescript tsd
    - npm install
    - tsd install
    - tslint --version
    - tsc --version
    - mkdir -p build/src/renderer

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3

script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p browser/
    - tsc -p renderer/
    - tsc tests/renderer/keyboard_test.ts --out tests/renderer/index.js
    - tsc -p tests/browser
    - npm test -- --travis

after_script:
    - rake release

deploy:
    provider: releases
    api_key: $GITHUB_RELEASE_TOKEN
    file:
        - packages/Shiba-darwin-x64.zip
        - packages/Shiba-linux-ia32.zip
        - packages/Shiba-linux-x64.zip
        - packages/Shiba-win32-ia32.zip
        - packages/Shiba-win32-x64.zip
    skip_cleanup: true
    on:
        tags: true

cache:
    - apt

addons:
    apt:
        packages:
            - xvfb
            - wine
