language: node_js
node_js:
    - "0.12.7"
sudo: false
install:
    - npm install -g tslint typescript tsd
    - npm install
    - tsd install
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - tslint --version
    - tsc --version
    - mkdir -p build/src/renderer
script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p src/browser/
    - tsc src/renderer/index.ts --out build/src/renderer/index.js
    - tsc src/renderer/markdown-preview.ts --out build/src/renderer/markdown-preview.js
    - tsc src/renderer/lint-panel.ts --out build/src/renderer/lint-panel.js
    - tsc src/renderer/path-dialog.ts --out build/src/renderer/path-dialog.js
    - tsc src/renderer/paw-filechooser.ts --out build/src/renderer/paw-filechooser.js
    - npm test -- --travis
addons:
    apt:
        packages:
            - xvfb
