language: node_js
node_js: stable
sudo: false

install:
    - npm install -g tslint typescript bower
    - gem install slim
    - npm install
    - ./node_modules/.bin/typings install
    - tslint --version
    - tsc --version
    - mkdir -p build/src/renderer
    - mkdir -p build/static

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p browser/
    - tsc -p renderer/

after_sccess:
    - |
        if [[ "$TRAVIS_TAG" ]]; then
            npm install -g electron-packger
            rake release
        fi

deploy:
    provider: releases
    api_key: $GITHUB_RELEASE_TOKEN
    file:
        - packages/Shiba-darwin-x64.zip
        - packages/Shiba-linux-ia32.zip
        - packages/Shiba-linux-x64.zip
        - packages/Shiba-win32-ia32.zip
        - packages/Shiba-win32-x64.zip
    skip_cleanup: true
    on:
        repo: rhysd/Shiba
        tags: true
        all_branches: true

cache:
    - apt

addons:
    apt:
        packages:
            - xvfb
            - wine
