language: node_js
node_js:
    - "0.12.7"
sudo: false
install:
    - npm install -g tslint typescript tsd
    - npm install
    - tsd install
    - tslint --version
    - tsc --version
    - mkdir -p build/src/renderer
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p src/browser/
    - tsc -p src/renderer/
    - tsc tests/renderer/keyboard_test.ts --out tests/renderer/index.js
    - tsc -p tests/browser
    - npm test -- --travis
addons:
    apt:
        packages:
            - xvfb
