language: node_js
node_js: stable

os:
    - linux
dist: trusty

install:
    - gem install slim
    - rake dep
    - ./node_modules/.bin/tslint --version
    - ./node_modules/.bin/tsc --version

script:
    - rake lint
    - rake compile
    - rake test

notifications:
    email:
        on_success: change
        on_failure: change
