language: node_js
node_js: stable
sudo: false

install:
    - npm install -g tslint typescript tsd bower electron-packager
    - gem install slim
    - npm install
    - tsd install
    - tslint --version
    - tsc --version
    - mkdir -p build/src/renderer
    - mkdir -p build/static

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - tslint $(git ls-files | grep '.ts$')
    - tsc -p browser/
    - tsc -p renderer/
    - if [[ "$TRAVIS_TAG" ]]; then rake release; fi

deploy:
    provider: releases
    api_key:
        secure: IPgoYOzTPyHubOgddXvB57mW/AWPpL3f/CSOOHGr6Q0i7G+vEW777i1GCi28vF2NS1rd5EOVn8vROJ2bXC1ZdtklbKPPpd7HXie2asXh+7c7a+q8hoKBR9Ifw9Xvb3fewyxCZjbAN3Mw6S46XHJ769ZDJ0QNcIJykgprPnvWw5vUnqGGkBUMZlBpp2DGbnINAJBQHLahuJ9BVhjCpSxkZJp3+Ck6Wzg2PBOKBJoDYOk4V3oHGbBngWjxInAsA8ozF6PIj7+gsgO3JFwkWLVZQwGD45zLF8x2otMKPPlzZXto6/Q88bWklYIFwQ3hryknPt3rvmr0YobBOPzcmQTpboWHsblwLrPkq7+TG1108oCdjcFek09o16YW7/IXcQuU5sxrAriE7MmTE0kwPnGn6nPcjQ7WDlZnqqwLfzPAgmCHxLVmnZmgIvlX5k6dZM0bRBDxWoAfifctH/bA5/TdAxdFysXacpPW7ZP4vXEa5u8jrE0gIS+mwvLfPkMdqUw/N1K9Mnass4QUpXTZCIXDhEbO+p6lnGxccHfHmrc3XgyROncFXn45l8yQBN5IiW4CnUcte9e01oAGyOzp2NIuz+uQx84jECuEMrRgXE8OYZaiN5zUa4YNhcsUz+cRBMSu6nseGwNEIGDErJ+YzR+VI69dXDG64ofuV6qdQhr9xCw=
    file:
        - packages/Shiba-darwin-x64.zip
        - packages/Shiba-linux-ia32.zip
        - packages/Shiba-linux-x64.zip
        - packages/Shiba-win32-ia32.zip
        - packages/Shiba-win32-x64.zip
    skip_cleanup: true
    on:
        repo: rhysd/Shiba
        tags: true
        all_branches: true

cache:
    - apt

addons:
    apt:
        packages:
            - xvfb
            - wine
